#ifndef NETWORK_DEFINE_H
#define NETWORK_DEFINE_H

#define DEFAULT_SESSION_NUM 128

//ROLE DEFINE
#define NETWORK_ROLE_UNKNOWN 0
#define NETWORK_ROLE_ACCEPT 1
#define NETWORK_ROLE_CLIENT 2

//state define
#define NETWORK_STATE_UNKNOWN 0
#define NETWORK_STATE_CONNECTED 1
#define NETWORK_STATE_UNCONNECTED 2
#define NETWORK_STATE_CONNECTING 3

//type
#define NETWORK_TYPE_UNKNOWN 0

#endif //NETWORK_DEFINE_H
